name: CI workflow

on:
  push:
    branches: 
     - 'feature/**'
  pull_request:
    branches:
     - 'main'

jobs:
  ci_job:
    name: CI job
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Set up Python
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # 3️⃣ Install dependencies + pytest-html
      - name: Install dependencies + pytest-html
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-pyspark.txt

      # 4️⃣ Run tests and generate HTML report
      - name: Run tests and generate HTML report
        run: |
          pytest \
          --disable-warnings \
          --cov=./src \
          --cov-report=html

      # 5 Upload coverage html report
      - name: Upload  coverage html report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-html
          path: htmlcov
